"""ISO3/ISO4 reference quantizer tests (kernel/iso.py).

Golden vectors were generated by the unmodified C reference implementation
(quantize_row_iso3_0_ref / quantize_row_iso4_0_ref) from the
llama-cpp-turbo-planar-iso fork; see iso_golden.npz.
"""

import pathlib

import numpy as np
import pytest
import torch

from freetoken.kernel import iso

GOLDEN = pathlib.Path(__file__).with_name("iso_golden.npz")


def test_quaternions_unit_norm():
    q = torch.tensor(list(zip(iso.ISO_QW, iso.ISO_QX, iso.ISO_QY, iso.ISO_QZ)))
    assert q.shape == (32, 4)
    assert torch.allclose(q.norm(dim=-1), torch.ones(32), atol=1e-6)


def test_block_layout():
    assert iso.block_bytes("iso3") == 50
    assert iso.block_bytes("iso4") == 68
    assert iso.packed_row_bytes(128, "iso3") == 50
    assert iso.packed_row_bytes(256, "iso3") == 100
    assert iso.packed_row_bytes(256, "iso4") == 136
    with pytest.raises(ValueError):
        iso.packed_row_bytes(96, "iso3")
    with pytest.raises(ValueError):
        iso.block_bytes("iso5")


@pytest.mark.parametrize("fmt,min_cos", [("iso3", 0.95), ("iso4", 0.97)])
def test_roundtrip(fmt, min_cos):
    torch.manual_seed(7)
    x = torch.randn(256, 256) * 4.0
    packed = iso.quantize_ref(x, fmt)
    assert packed.dtype == torch.uint8
    assert packed.shape == (256, iso.packed_row_bytes(256, fmt))
    deq = iso.dequantize_ref(packed, fmt, 256)
    cos = torch.nn.functional.cosine_similarity(x, deq, dim=-1)
    assert cos.min() > min_cos
    # corrected norm: reconstructed norm matches input up to fp16 rounding
    rel = (deq.norm(dim=-1) - x.norm(dim=-1)).abs() / x.norm(dim=-1)
    assert rel.max() < 2e-3
    # determinism
    assert torch.equal(packed, iso.quantize_ref(x, fmt))


def test_zero_row():
    x = torch.zeros(3, 128)
    for fmt in ("iso3", "iso4"):
        deq = iso.dequantize_ref(iso.quantize_ref(x, fmt), fmt, 128)
        assert torch.equal(deq, torch.zeros_like(deq))


def test_golden_bitexact():
    """Byte-exact match against the fork's C reference quantizer."""
    data = np.load(GOLDEN)
    x = torch.from_numpy(data["x"])
    for fmt in ("iso3", "iso4"):
        mine = iso.quantize_ref(x, fmt).numpy()
        assert np.array_equal(mine, data[fmt]), f"{fmt} payload mismatch vs C reference"


def test_bad_shapes():
    with pytest.raises(ValueError):
        iso.quantize_ref(torch.randn(4, 100), "iso3")
    with pytest.raises(ValueError):
        iso.dequantize_ref(torch.zeros(4, 51, dtype=torch.uint8), "iso3", 128)


@pytest.mark.skipif(not torch.cuda.is_available(), reason="no CUDA")
@pytest.mark.parametrize("fmt", ["iso3", "iso4"])
def test_cuda_matches_cpu(fmt):
    torch.manual_seed(11)
    x = torch.randn(32, 256) * 2.0
    cpu = iso.quantize_ref(x, fmt)
    gpu = iso.quantize_ref(x.cuda(), fmt).cpu()
    assert torch.equal(cpu, gpu)
    assert torch.equal(
        iso.dequantize_ref(cpu, fmt, 256), iso.dequantize_ref(gpu.cuda(), fmt, 256).cpu()
    )
